// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj-IabhtSEyaBVbmiT2Q-70RaeRj0l1PI',
    appId: '1:882473022030:web:35f3a5e8991e7c393e091f',
    messagingSenderId: '882473022030',
    projectId: 'turfix-turf-booking',
    authDomain: 'turfix-turf-booking.firebaseapp.com',
    storageBucket: 'turfix-turf-booking.firebasestorage.app',
    measurementId: 'G-Y0C14BDQ6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClVaQwM3tS0rsOk7Nek2PpkdPqDxiwlLU',
    appId: '1:882473022030:android:951465ce584b1c133e091f',
    messagingSenderId: '882473022030',
    projectId: 'turfix-turf-booking',
    storageBucket: 'turfix-turf-booking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTtTR_kHgL5_RgcIhTDxZW4xS7X3FBOvs',
    appId: '1:882473022030:ios:9ce27ba539e668293e091f',
    messagingSenderId: '882473022030',
    projectId: 'turfix-turf-booking',
    storageBucket: 'turfix-turf-booking.firebasestorage.app',
    iosBundleId: 'com.example.turfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTtTR_kHgL5_RgcIhTDxZW4xS7X3FBOvs',
    appId: '1:882473022030:ios:9ce27ba539e668293e091f',
    messagingSenderId: '882473022030',
    projectId: 'turfix-turf-booking',
    storageBucket: 'turfix-turf-booking.firebasestorage.app',
    iosBundleId: 'com.example.turfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj-IabhtSEyaBVbmiT2Q-70RaeRj0l1PI',
    appId: '1:882473022030:web:10c2363f53ed80e83e091f',
    messagingSenderId: '882473022030',
    projectId: 'turfix-turf-booking',
    authDomain: 'turfix-turf-booking.firebaseapp.com',
    storageBucket: 'turfix-turf-booking.firebasestorage.app',
    measurementId: 'G-8TNK36XED1',
  );
}
